# Copyright (C) 2010-2015 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file "docs/LICENSE" for copying permission.

from django.conf.urls import url
from api.views import (index, tasks_create_file, tasks_create_url, tasks_vtdl, tasks_search, ext_tasks_search,
                       tasks_list, tasks_view, tasks_reschedule, tasks_delete, tasks_status, tasks_report,
                       tasks_iocs, tasks_screenshot, tasks_procmemory, tasks_fullmemory, tasks_pcap,
                       tasks_dropped, tasks_surifile, files_view, get_files, machines_list, machines_view,
                       cuckoo_status, tasks_rollingsuri, tasks_rollingshrike)

urlpatterns = [
    url(r"^$", index),
    url(r"^tasks/create/file/$", tasks_create_file),
    url(r"^tasks/create/url/$", tasks_create_url),
    url(r"^tasks/create/vtdl/$", tasks_vtdl),
    url(r"^tasks/search/md5/(?P<md5>([a-fA-F\d]{32}))/$", tasks_search),
    url(r"^tasks/search/sha1/(?P<sha1>([a-fA-F\d]{40}))/$", tasks_search),
    url(r"^tasks/search/sha256/(?P<sha256>([a-fA-F\d]{64}))/$", tasks_search),
    url(r"^tasks/extendedsearch/$", ext_tasks_search),
    url(r"^tasks/list/$", tasks_list),
    url(r"^tasks/list/(?P<limit>\d+)/$", tasks_list),
    url(r"^tasks/list/(?P<limit>\d+)/(?P<offset>\d+)/$", tasks_list),
    url(r"^tasks/list/(?P<limit>\d+)/(?P<offset>\d+)/(?P<window>\d+)/$", tasks_list),
    url(r"^tasks/view/(?P<task_id>\d+)/$", tasks_view),
    url(r"^tasks/reschedule/(?P<task_id>\d+)/$", tasks_reschedule),
    url(r"^tasks/delete/(?P<task_id>\d+)/$", tasks_delete),
    url(r"^tasks/status/(?P<task_id>\d+)/$", tasks_status),
    url(r"^tasks/get/report/(?P<task_id>\d+)/$", tasks_report),
    url(r"^tasks/get/report/(?P<task_id>\d+)/(?P<report_format>\w+)/$", tasks_report),
    url(r"^tasks/get/iocs/(?P<task_id>\d+)/$", tasks_iocs),
    url(r"^tasks/get/iocs/(?P<task_id>\d+)/(?P<detail>detailed)/$", tasks_iocs),
    url(r"^tasks/get/screenshot/(?P<task_id>\d+)/$", tasks_screenshot),
    url(r"^tasks/get/screenshot/(?P<task_id>\d+)/(?P<screenshot>\d{1,4})/$", tasks_screenshot),
    url(r"^tasks/get/procmemory/(?P<task_id>\d+)/$", tasks_procmemory),
    url(r"^tasks/get/procmemory/(?P<task_id>\d+)/(?P<pid>\d{1,5})/$", tasks_procmemory),
    url(r"^tasks/get/fullmemory/(?P<task_id>\d+)/$", tasks_fullmemory),
    url(r"^tasks/get/pcap/(?P<task_id>\d+)/$", tasks_pcap),
    url(r"^tasks/get/dropped/(?P<task_id>\d+)/$", tasks_dropped),
    url(r"^tasks/get/surifile/(?P<task_id>\d+)/$", tasks_surifile),
    url(r"^files/view/md5/(?P<md5>([a-fA-F\d]{32}))/$", files_view),
    url(r"^files/view/sha1/(?P<sha1>([a-fA-F\d]{40}))/$", files_view),
    url(r"^files/view/sha256/(?P<sha256>([a-fA-F\d]{64}))/$", files_view),
    url(r"^files/view/id/(?P<sample_id>\d+)/$", files_view),
    url(r"^files/get/(?P<stype>md5)/(?P<value>([a-fA-F\d]{32}))/$", get_files),
    url(r"^files/get/(?P<stype>sha1)/(?P<value>([a-fA-F\d]{40}))/$", get_files),
    url(r"^files/get/(?P<stype>sha256)/(?P<value>([a-fA-F\d]{64}))/$", get_files),
    url(r"^files/get/(?P<stype>task)/(?P<value>\d+)/$", get_files),
    url(r"^machines/list/$", machines_list),
    url(r"^machines/view/(?P<name>[\w$-/:-?{-~!^_`\[\]]+)/$", machines_view),
    url(r"^cuckoo/status/$", cuckoo_status),
    url(r"^tasks/get/rollingsuri/(?P<window>\d+)/$", tasks_rollingsuri),
    url(r"^tasks/get/rollingshrike/(?P<window>\d+)/$", tasks_rollingshrike),
    url(r"^tasks/get/rollingshrike/(?P<window>\d+)/(?P<msgfilter>[\w$-/:-?{-~!^_`\[\]\s\x5c]+)/$", tasks_rollingshrike),
]
